#ifndef NFC_MESSAGES_H
#define NFC_MESSAGES_H
// Warning this file is auto-generated by dataGenerator.py
// Do not edit this file directly or your changes will be lost on a subsequent run.

#include <stdint.h>

// NFC messages 
// "Test 1"
const uint8_t dat0[] = {0XE1, 0X40, 0X40, 0X00, 0X03, 0X0B, 0XD1, 0X01, 0X07, 0X55, 0X00, 0X54, 0X65, 0X73, 0X74, 0X20, 0X31, 0XFE};
// "Test 2 a bit longer"
const uint8_t dat1[] = {0XE1, 0X40, 0X40, 0X00, 0X03, 0X18, 0XD1, 0X01, 0X14, 0X55, 0X00, 0X54, 0X65, 0X73, 0X74, 0X20, 0X32, 0X20, 0X61, 0X20, 0X62, 0X69, 0X74, 0X20, 0X6C, 0X6F, 0X6E, 0X67, 0X65, 0X72, 0XFE};
// "Test 3 even looooooooooooooooooooooooooonger"
const uint8_t dat2[] = {0XE1, 0X40, 0X40, 0X00, 0X03, 0X31, 0XD1, 0X01, 0X2D, 0X55, 0X00, 0X54, 0X65, 0X73, 0X74, 0X20, 0X33, 0X20, 0X65, 0X76, 0X65, 0X6E, 0X20, 0X6C, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6F, 0X6E, 0X67, 0X65, 0X72, 0XFE};
// "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
const uint8_t dat3[] = {0XE1, 0X40, 0X40, 0X00, 0X03, 0X24, 0XD1, 0X01, 0X20, 0X55, 0X02, 0X79, 0X6F, 0X75, 0X74, 0X75, 0X62, 0X65, 0X2E, 0X63, 0X6F, 0X6D, 0X2F, 0X77, 0X61, 0X74, 0X63, 0X68, 0X3F, 0X76, 0X3D, 0X64, 0X51, 0X77, 0X34, 0X77, 0X39, 0X57, 0X67, 0X58, 0X63, 0X51, 0XFE};
// "spotify:track:4cOdK2wGLETKBW3PvgPWqT"
const uint8_t dat4[] = {0XE1, 0X40, 0X40, 0X00, 0X03, 0X29, 0XD1, 0X01, 0X25, 0X55, 0X00, 0X73, 0X70, 0X6F, 0X74, 0X69, 0X66, 0X79, 0X3A, 0X74, 0X72, 0X61, 0X63, 0X6B, 0X3A, 0X34, 0X63, 0X4F, 0X64, 0X4B, 0X32, 0X77, 0X47, 0X4C, 0X45, 0X54, 0X4B, 0X42, 0X57, 0X33, 0X50, 0X76, 0X67, 0X50, 0X57, 0X71, 0X54, 0XFE};

// array of pointer to messages
const uint8_t *nfcMessages[] = {dat0, dat1, dat2, dat3, dat4};

// Number of messages
const uint8_t messageNumber = 5;

#endif // NFC_MESSAGES_H